name: CI Pipeline

on:
  push:
    branches: [main]  # Запускать только при пуше в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем GitHub-hosted runner с Ubuntu

    steps:
      - uses: actions/checkout@v3  # Клонирует код из репозитория

      - name: Встановлення залежностей
        run: npm ci

      - name: Линтинг
        run: npm run lint

      - name: Запуск тестів
        run: npm run test

      - name: Зборка
        run: docker build -t ${{ secrets.DOCKER_USER }}/devops-node-starter:${{ github.sha }} .